# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trufflego < Formula
  desc "Find (possible) secrets in a directory"
  homepage "https://github.com/mantro/trufflego"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mantro/trufflego/releases/download/v0.0.4/trufflego_0.0.4_Darwin_arm64.tar.gz"
      sha256 "64e64d106d9c242573df2b2d7c5651185a9c7f7a6dcbb29e52bcdb5e4f9c2403"

      def install
        bin.install "trufflego"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mantro/trufflego/releases/download/v0.0.4/trufflego_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "2d35ff8dacb9fc10d96db877c36d125f1044ab370562bbe45dfb536012f0cf86"

      def install
        bin.install "trufflego"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mantro/trufflego/releases/download/v0.0.4/trufflego_0.0.4_Linux_arm64.tar.gz"
      sha256 "8fb2745a2deeb86b5cd8df26d14b543122df2b6d843d9cf4fda0e43c826cb2b6"

      def install
        bin.install "trufflego"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mantro/trufflego/releases/download/v0.0.4/trufflego_0.0.4_Linux_x86_64.tar.gz"
      sha256 "1dc6950fc50097078a11886ea968877a6abfefd260bfc54c74cb604cf167eeb2"

      def install
        bin.install "trufflego"
      end
    end
  end
end
